name: Update News Feed

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-news:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_PAT }}
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Fetch news and NBA scores
      env:
        GNEWS_API_KEY: ${{ secrets.GNEWS_API_KEY }}
      run: |
        python scripts/fetch_news.py
        python scripts/fetch_nba.py
    
    - name: Commit and push if changed
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add data/news.json data/nba_cache.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update news feed and NBA scores" && git push https://$GH_PAT@github.com/$GITHUB_REPOSITORY.git) 